apiVersion: v1
kind: Service
metadata:
  name: washbin-service
spec:
  type: LoadBalancer
  selector:
    app: washbinsite
  ports:
    - protocol: TCP
      port: 90
      targetPort: 5000
      
      
